name = "stortinget-rss-worker"
main = "build/index.js"
compatibility_date = "2025-12-18"

[triggers]
crons = ["*/15 * * * *"]

[vars]
FEED_URL = "https://www.stortinget.no/no/Stottemeny/RSS/Lovbeslutninger/"

[build]
command = "cargo install -q worker-build@^0.7 && worker-build --release"